version: '3.8'

services:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=users
      - DB_USER=root
      - DB_PASSWORD=secret
      - DATABASE_URI=mysql+pymysql://root:secret@db:3306/users
      - JWT_SECRET_KEY=informations-sur-les-utilisateurs
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  mysql-data:
